baseURL: https://kpostigo.github.io/
languageCode: en-us
title: postigo.fyi
theme: PaperMod

menu:
  main:
      - identifier: boo
        name: 404
        url: /boo/
        weight: 10

enableEmoji: true

params:
  cover:
    hiddenInList: true
    hiddenInSingle: false

  showReadingTime: true
  showShareButtons: true

  homeInfoParams:
    imageUrl: images/me.jpeg
    imageTitle: me
    title: ":cooking: Kenneth Postigo"
    content: |
      hardware and software engineer by profession.

      deep interests in finance, food, fashion, music, and design over all.  

  socialIcons:
    - name: github
      url: https://github.com/kpostigo
    - name: twitter
      url: https://twitter.com/postigo_txt