baseURL: https://kpostigo.github.io/
languageCode: en-us
title: postigo.fyi
theme: PaperMod

menu:
#   main:
#       - identifier: boo
#         name: 404
#         url: /boo/
#         weight: 10

enableEmoji: true

params:
  defaultTheme: light
  disableThemeToggle: true

  cover:
    hiddenInList: true
    hiddenInSingle: false

  showReadingTime: true
  showShareButtons: true
  custom:
    ShareButtons:
      twitter: false
      linkedin: false
  showToc: true

  homeInfoParams:
    imageUrl: images/me.jpeg
    imageTitle: me
    title: ":cooking: Kenneth Postigo"
    content: |
      hardware & software engineer

      passionate about finance, food, fashion, music, and design.

  socialIcons:
    - name: github
      url: https://github.com/kpostigo
    - name: twitter
      url: https://twitter.com/postigo_txt